### ISSUE TITLE
Restart driver insteed of restart computer

### ISSUE THREAD

**Issue by UnclWish** [ColossusFX/AMDComputeModeEnable#1]
It's better make to restart driver insteed of restart computer like it's made by AMD via Radeon Settings.

**Comment by ColossusFX** [comment]
This was just a quick hack job to speed up changing settings. 

Restarting pc isn’t a big deal with an SSD drive really.

I don’t think I’ll have time to look at restarting drivers etc

**Comment by UnclWish** [comment]
Did you think that opening Radeon Settings and go to global settings to change workload isn't so hard. But it don't requre restart...
I don't see a benefit from your script, really... But it's IMHO. Maybe others have other opinion...

**Comment by ColossusFX** [comment]
Using AMD settings you have to do 1 card, then wait for app restart, and the app is super slow.

Doing this for lots of rigs and cards is very tedious.

This script sets all cards to compute mode in under a second.

This is mainly for my own use, but uploaded it Incase it is of use to others.

Plus I don’t think the restart is necessary when setting in registry.

**Comment by UnclWish** [comment]
Agreed. For large amount of cards it's will be usefull.
Restart driver needed, you can check this.
Close than.
